name: Export to CoreML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Set up Git LFS
        run: |
          brew install git-lfs || true
          git lfs install
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export to CoreML
        run: python export_coreml.py
        
      - name: Convert to mlmodelc
        run: |
          xcrun coremlcompiler compile ColoringBook.mlpackage/Data/com.apple.CoreML/model.mlmodel ColoringBook.mlmodelc
          
      - name: Configure Git LFS and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git lfs track "*.bin"
          git lfs track "*.mlmodel"
          git add .gitattributes
          find . -name "*.bin" -o -name "*.mlmodel" | xargs git add
          git add ColoringBook.mlpackage ColoringBook.mlmodelc
          git commit -m "Update CoreML model with compiled version" || exit 0
          git lfs push --all origin main
          git push origin main
