name: Export to CoreML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export to CoreML
        run: python export_coreml.py
        
      - name: Convert to mlmodelc
        run: |
          xcrun coremlcompiler compile ColoringBook.mlpackage/Data/com.apple.CoreML/model.mlmodel ColoringBook.mlmodelc
          tar -czf ColoringBook.mlmodelc.tar.gz ColoringBook.mlmodelc/

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a release with current date
          release_name="CoreML-Model-$(date +'%Y%m%d')"
          gh release create $release_name ColoringBook.mlmodelc.tar.gz \
            --title "CoreML Model Release $(date +'%Y-%m-%d')" \
            --notes "Compiled CoreML model for iOS" \
            --draft=false
