name: Export to CoreML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export to CoreML
        run: python export_coreml.py

      - name: Upload CoreML model
        uses: actions/upload-artifact@v3
        with:
          name: ColoringBook-CoreML
          path: ColoringBook.mlpackage
          if-no-files-found: error
