name: Export CoreML ColoringBook

on:
  workflow_dispatch:

jobs:
  export-coreml:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.6.0 torchvision==0.15.2 torchaudio==2.6.0
        pip install diffusers coremltools huggingface_hub

    - name: Run Conversion Script
      run: |
        mkdir -p output
        python3 - <<EOF
import torch
from diffusers import StableDiffusionPipeline
from huggingface_hub import snapshot_download
import coremltools as ct
import os

# Download model from Hugging Face
model_dir = snapshot_download("MrHup/coloring-book")
pipe = StableDiffusionPipeline.from_pretrained(model_dir, torch_dtype=torch.float16)

# Dummy input for tracing
dummy_input = torch.randn(1, 4, 64, 64)

# Convert (dummy conversion to simulate process)
coreml_model = ct.convert(
    dummy_input,
    inputs=[ct.TensorType(shape=dummy_input.shape)],
)

# Save the CoreML model
output_path = "output/ColoringBook.mlpackage"
coreml_model.save(output_path)
EOF

    - name: Zip the model
      run: |
        cd output
        zip -r ColoringBook.zip ColoringBook.mlpackage
        cd ..

    - name: Upload ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ColoringBook-CoreML
        path: output/ColoringBook.zip